name: curvvaecuda
channels:
  - anaconda
  - pytorch
  - defaults
dependencies:
  - python>=3.6,<3.7
  - tensorboard==2.1.0
  - pip>=20.2.4
  - pytorch=1.7.1
  - matplotlib
  - numpy 
  - opencv
  - jupyterlab
  - scipy
  - scikit-learn
  - pillow
  - statsmodels
  - pip:
    - transforms3d
